Added support for deleting rights on resources from resourceregistry
Altinn/altinn-access-management pull request #149
Opened 2022-10-19 04:44 UTC by Sondre-B

…in the DeleteRules operation.

## Description
Added support for deleting rights on resources from resourceregistry in the DeleteRulesOperation. It is now posible to pass ResourceRegistryId for a resource to have the rights revoked.

## Related Issue(s)
- #71

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2022-10-19 08:52 UTC, jonkjetiloye requested changes

2022-10-19 08:52 UTC, jonkjetiloye commented on backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin/Services/Implementation/PolicyAdministrationPoint.cs
> -            if (resourceMatchType != ResourceAttributeMatchType.AltinnApp)
Still should check the result of the TryGetResourceFromAttributeMatch operation. If it fails and/or the resourceMatchType is none operation should fail as the resource cannot be identified

2022-10-19 08:52 UTC, jonkjetiloye commented on backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin/Services/Implementation/PolicyAdministrationPoint.cs
> -            if (resourceMatchType != ResourceAttributeMatchType.AltinnApp)
Same here as in DeleteAllRulesInPolicy:
Still should check the result of the TryGetResourceFromAttributeMatch operation. If it fails and/or the resourceMatchType is none operation should fail as the resource cannot be identified

2022-10-19 08:52 UTC, jonkjetiloye commented on backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin/Services/Implementation/PolicyAdministrationPoint.cs
>              try
LogError for catched exception for this try is still org/app specific

2022-10-19 10:47 UTC, jonkjetiloye commented on backend/src/Altinn.Authorizationadmin/Altinn.AuthorizationAdmin.Tests/Data/blobs/input/resourceregistry/resource2/50001337/u20001337/delegationpolicy.xml
> +	<xacml:Description>Delegation policy containing all delegated rights/actions from 50001337 to 20001337, for resources on the app; org1/app3</xacml:Description>
copy/pasted description

2022-10-19 10:47 UTC, jonkjetiloye commented on backend/src/Altinn.Authorizationadmin/Altinn.AuthorizationAdmin.Tests/Altinn.AuthorizationAdmin.Tests.csproj
> +  <ItemGroup>
Please remove all project file clutter for individual files under the Data folder, which should be unnecessary and already covered by the catch all item group.

2022-10-19 10:47 UTC, jonkjetiloye commented on backend/src/Altinn.Authorizationadmin/Altinn.AuthorizationAdmin.Tests/DelegationsControllerTest.cs
> +                TestDataUtil.GetRuleModel(20001336, 50001337, "20001337", AltinnXacmlConstants.MatchAttributeIdentifiers.UserAttribute, "read", null, null, createdSuccessfully: true, resourceRegistry
createdSuccessfully is irrelevant for a delete operation. 
Should set the expected ruleIds which are to be deleted for verification against the response

2022-10-19 10:47 UTC, jonkjetiloye commented on backend/src/Altinn.Authorizationadmin/Altinn.AuthorizationAdmin.Tests/DelegationsControllerTest.cs
> +        public async Task Post_DeleteResourceRegistryRules_Success()
should also add test for DeletePolicy

2022-10-19 10:47 UTC, jonkjetiloye commented on backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin/Services/Implementation/PolicyAdministrationPoint.cs
> +            resource = await _resourceRegistryClient.GetResource(resourceregistryId);
Resource lookup should only be performed if resourceRegistryId has a value

2022-10-19 10:47 UTC, jonkjetiloye commented on backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin/Services/Implementation/PolicyAdministrationPoint.cs
> +            resource = await _resourceRegistryClient.GetResource(resourceRegistryId);
same here, use resourceMatchType.ResourceRegistry for specific logic as _resourceRegistryClient should not be used for altinn app scenario

2022-10-19 10:47 UTC, jonkjetiloye commented on backend/src/Altinn.Authorizationadmin/Altinn.AuthorizationAdmin.Tests/DelegationsControllerTest.cs
> +        public async Task Post_DeleteResourceRegistryRules_Success()
Should also have negative tests? E.g.
- Delete request without valid resource must fail

2022-10-19 10:47 UTC, jonkjetiloye commented on backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin/Services/Implementation/PolicyAdministrationPoint.cs
> +            resource = await _resourceRegistryClient.GetResource(resourceregistryId);
but also unsure whether we need to actually lookup the resource in the registry for delete operation. 
Should perhaps be enough that the delegation policy exist and we are able to get a lease lock for the blob?

2022-11-03 11:17 UTC, Sondre-B commented
Closing this PR, replaced by https://github.com/Altinn/altinn-access-management/pull/170.

2022-11-03 11:17 UTC, closed without merging