Enable deleting rights on resources from resourceregistry
Altinn/altinn-access-management pull request #170
Opened 2022-10-28 07:45 UTC by Sondre-B

## Description
Moved changes from pull request 149 into this branch to enable merging with main branch that has had its filestructure changed.

## Related Issue(s)
- #150 

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2022-10-31 12:03 UTC, jonkjetiloye requested changes

2022-11-01 08:36 UTC, Sondre-B commented on src/Altinn.AccessManagement/Services/Implementation/PolicyAdministrationPoint.cs
> +                DelegationChange currentChange = await _delegationRepository.GetCurrentDelegationChange(altinnAppId, resourceregistryId, deleteRequest.PolicyMatch.OfferedByPartyId, coveredByPartyId,
Made an if statement to trigger different error message depending on resourceRegistryId/altinnappId. Also tried searching for more occurrences but did not find any this time.

2022-11-02 12:57 UTC, Sondre-B commented on test/Altinn.AccessManagement.Tests/PolicyAdministrationPointTest.cs
18 tests in this class related to deleting of policies are currently failing after merge. Looking into it.

2022-11-07 09:25 UTC, jonkjetiloye approved these changes

2022-11-09 16:26 UTC, merged